"""VPN Gate 网络类型关键词和国家名称，沿用参考项目。"""

DATA_CENTER_ORG_KEYWORDS = (
    "GOOGLE",
    "AMAZON",
    "AWS",
    "MICROSOFT",
    "OVH",
    "HETZNER",
    "DIGITALOCEAN",
    "AKAMAI",
    "CLOUDFLARE",
    "FASTLY",
    "RACKSPACE",
    "EQUINIX",
    "LINODE",
    "VULTR",
    "HURRICANE",
    "TENCENT",
    "ALIBABA",
    "ALIYUN",
    "LEASWEB",
)
RESIDENTIAL_ORG_KEYWORDS = (
    "NTT EAST",
    "NTT WEST",
    "NTT COMMUNICATIONS",
    "NTT BROADBAND",
    "KDDI",
    "DOCOMO",
    "SOFTBANK",
    "AU COMMUNICATIONS",
    "J:COM",
    "JCOM",
    "OCN",
    "BIGLOBE",
    "IIJ",
    "SEIKO",
    "CLEVER-NET",
    "AT&T",
    "COMCAST",
    "XFINITY",
    "VERIZON",
    "TELUS",
    "ROGERS",
    "BELL CANADA",
    "VODAFONE",
    "ORANGE",
    "DEUTSCHE TELEKOM",
    "BREEZE",
    "TIM S.P.A",
    "LIBERO",
    "FASTWEB",
    "FREE FRANCE",
    "BT OPEN",
)
COUNTRY_ZH = {
    "JP": "日本",
    "KR": "韩国",
    "US": "美国",
    "CA": "加拿大",
    "RU": "俄罗斯",
    "RO": "罗马尼亚",
    "TH": "泰国",
    "VN": "越南",
    "DE": "德国",
    "FR": "法国",
    "GB": "英国",
    "UK": "英国",
    "SG": "新加坡",
    "TW": "台湾",
    "HK": "香港",
    "CN": "中国",
    "AU": "澳大利亚",
    "NL": "荷兰",
    "SE": "瑞典",
    "CH": "瑞士",
    "IT": "意大利",
    "ES": "西班牙",
    "PL": "波兰",
    "IN": "印度",
    "BR": "巴西",
    "MX": "墨西哥",
    "ID": "印度尼西亚",
    "MY": "马来西亚",
    "PH": "菲律宾",
    "TR": "土耳其",
    "UA": "乌克兰",
    "CZ": "捷克",
    "GR": "希腊",
    "PT": "葡萄牙",
    "FI": "芬兰",
    "NO": "挪威",
    "DK": "丹麦",
    "IE": "爱尔兰",
    "BE": "比利时",
    "AT": "奥地利",
    "HU": "匈牙利",
    "AR": "阿根廷",
    "CL": "智利",
    "CO": "哥伦比亚",
    "NZ": "新西兰",
    "ZA": "南非",
    "IL": "以色列",
    "AE": "阿联酋",
    "SA": "沙特",
    "EG": "埃及",
    "HR": "克罗地亚",
    "BY": "白俄罗斯",
    "GD": "格林纳达",
    "LV": "拉脱维亚",
    "EE": "爱沙尼亚",
    "LT": "立陶宛",
    "SK": "斯洛伐克",
    "SI": "斯洛文尼亚",
    "BG": "保加利亚",
    "RS": "塞尔维亚",
    "GE": "格鲁吉亚",
    "MD": "摩尔多瓦",
    "AM": "亚美尼亚",
    "KZ": "哈萨克斯坦",
    "UZ": "乌兹别克斯坦",
    "MN": "蒙古",
    "NP": "尼泊尔",
    "LK": "斯里兰卡",
    "MM": "缅甸",
}
